### ISSUE TITLE
Create a RZTransition NavigationDelegate Helper

### ISSUE THREAD

**Issue by smbarne** [Raizlabs/RZTransitions#1]
## Create an object that can be assigned as the nav controller's delegate for transitions.  

 - [ ] It should contain a map of what VC classes to transition between and what transition to use.  
 - [ ] It should have a default transition to use if no specific mappings are found
 - [ ] It should set the positive or negative direction on an RZTransition if the transition complies with the protocol based on a push or pop.

---

## Optional / Further Work

 - [ ] Create an object that can be assigned as the transition delegate.  It should handle present and dismiss animations.  If possible, this object could/should be the same as the nav controller delegate helper.

**Comment by mr-fixit** [comment]
Hey, Steve, do you mind if I unassign you on this issue?

**Comment by smbarne** [comment]
Sure.  Reading through this, I believe this might be handled by `RZTransitionManager` and might be an old issue.

**Comment by mr-fixit** [comment]
I agree.
