### ISSUE TITLE
RZVerticalSwipeInteractionController Bug

### ISSUE THREAD

**Issue by fladdict** [Raizlabs/RZTransitions#15]
Seems it breaks up UIViewController hierarchy in some situation.

1: Run RZTransition-Demo. 
2: Push "present" and open modal view,
3: Swipe down view with interaction transitioning.
4: While swiping down, swiping up  and try to cancel.
5: It breaks transition and present modal view action.

**Comment by wongzigii** [comment]
Yes, I think this is a bug too. Also, the console outputs:
`Demo[22217:737916] Warning: Attempt to present <RZSimpleColorViewController: 0x7fe5f243c520>  on <RZSimpleViewController: 0x7fe5f241feb0> which is already presenting (null)`

**Comment by mr-fixit** [comment]
I see the bug too, and have a fix in the wings.  Hold tight.

**Comment by mr-fixit** [comment]
I believe this is fixed by PR #29
