### ISSUE TITLE
RZZoomPushAnimationController calls viewWillAppear:

### ISSUE THREAD

**Issue by nburatovich** [Raizlabs/RZTransitions#20]
My UIViewController had its viewWillAppear: method getting called twice – once by RZZoomPushAnimationController and then again by the system, causing some unnecessary work to be done.  RZZoomPushAnimationController's animateTransition: method explicitly calls `[toViewController viewWillAppear:YES]`.  This seems wrong to me because the system already automatically calls UIViewController's viewWillAppear: when appropriate.

I haven't read any documentation to indicate that viewWillAppear: should ever be explicitly called.  Is its use here an undocumented bug workaround or does it need to be called for any reason?  I removed it (because that seems like the better alternative than adding a guard to viewWillAppear:) and everything works as expected now (work is not done twice).

**Comment by mr-fixit** [comment]
thanks for the catch, and sorry for the delay in responding.  I just merged the fix to develop, in the PR #33
