### ISSUE TITLE
RZCirclePushAnimationController dismiss background Black,so bad UE Experience

### ISSUE THREAD

**Issue by wujiangwei** [Raizlabs/RZTransitions#41]
When set default Present VC
user RZCirclePushAnimationController
While enter vc,good circle looking
But~~~!!!!
When leave,after the circle animation,is black,bad looking
While animation finished,User be dazzled,so bad

can you fix this QA?
Very think!

**Comment by mr-fixit** [comment]
Thanks for the issue report.  Do you have sample code that shows the bug?

**Comment by wujiangwei** [comment]
Just You Sample on Git，Run the sample project,Enter main VC, Click [Present] Button，The enter the color VC,then click color VC,when close it:
While the animation not finished,Just like image after
[This is not a bug,Just not Greater]
![image](http://ac-bfrdmyeb.clouddn.com/0fa1cf1df0c2b856.png)

**Comment by mr-fixit** [comment]
I think I see what you mean.  You'd like the area outside the circle to show the 'from view', not black.  Right?

**Comment by wujiangwei** [comment]
Yes,I think if not black,it will be greater!

**Comment by wujiangwei** [comment]
Can you help refine this?

**Comment by wujiangwei** [comment]
While this animation finished,User will be dazzled(full black to full white or other color)

**Comment by dostrander** [comment]
@mr-fixit Can we close this issue? It looks like it was address with #42

**Comment by mr-fixit** [comment]
Yes, sorry!
