### ISSUE TITLE
Cross fade like iOS 7  / pixelated animation while transitioning form one controller to another

### ISSUE THREAD

**Issue by hammad** [Raizlabs/RZTransitions#43]
I want to have a pixelation or iOS 7 style cross fade animation when presenting a new controller, any help will be appreciated.

**Comment by mr-fixit** [comment]
Have you looked at Apple's [View Controller Programming Guide for iOS](https://developer.apple.com/library/ios/featuredarticles/ViewControllerPGforiPhoneOS/index.html#//apple_ref/doc/uid/TP40007457)?

Also, [this stackoverflow answer](http://stackoverflow.com/questions/10961926/how-do-i-do-a-fade-no-transition-between-view-controllers) might be exactly what you want.

If neither of those help, you'll get a quicker/better response by asking your question(s) on [stackoverflow](www.stackoverflow.com).

**Comment by hammad** [comment]
Basically wanted something like this: 

https://github.com/Raizlabs/RZTransitions/issues/44
