### ISSUE TITLE
Zoom out from a Point animation.

### ISSUE THREAD

**Issue by hammad** [Raizlabs/RZTransitions#44]
Basically i am trying write an animation where the presented controller expends from a fixed x,y point. something like: https://dl.dropboxusercontent.com/u/21062535/animation.mov Also when dismissed the presented controller should shrink back into that x,y position.

**Comment by Haidery** [comment]
HI @hammad . Check out this PR https://github.com/Raizlabs/RZTransitions/pull/45. This how you can use it.

```
    RZZoomFromPointAnimationController *animation = [[RZZoomFromPointAnimationController alloc] init];
    animation.origin= CGPointMake(1, 1);
    animation.color= [UIColor redColor];
    
    
    [[RZTransitionsManager shared] setAnimationController:animation
                                       fromViewController:[self class]
                                                forAction:RZTransitionAction_PresentDismiss];
```

values of origin are 0-1 instead of fixed x,y.

**Comment by hammad** [comment]
@Haidery  Ok it worked flawlessly!!
