### ISSUE TITLE
Singleton pattern

### ISSUE THREAD

**Issue by eugeniobaglieri** [Raizlabs/RZTransitions#50]
Should RZTransitionsManager be used always as a singleton?
I have 2 Separated navigation controller and i want assign a default different transition to each.
Is it possible?

**Comment by mr-fixit** [comment]
Yes, RZTransitionsManager is a singleton.  

To use a different animation for each navigation controller, you call `setAnimationController` on the singleton, passing in the animation controller, the 'from' VC-class and (optionally) a 'to' VC-class.
